#!/bin/bash
# Boost Software License - Version 1.0 - August 17th, 2003
#
# Copyright (c) 2026 Ian Torres
#
# Permission is hereby granted, free of charge, to any person or organization
# obtaining a copy of the software and accompanying documentation covered by
# this license (the "Software") to use, reproduce, display, distribute,
# execute, and transmit the Software, and to prepare derivative works of the
# Software, and to permit third-parties to whom the Software is furnished to
# do so, all subject to the following:
#
# The copyright notices in the Software and this entire statement, including
# the above license grant, this restriction and the following disclaimer,
# must be included in all copies of the Software, in whole or in part, and
# all derivative works of the Software, unless such copies or derivative
# works are solely in the form of machine-executable object code generated by
# a source language processor.
set -euo pipefail

BOOST_VERSION="${BOOST_VERSION:-1.92.0_b1}"
BUILD_VARIANT="${BUILD_VARIANT:-Release}"
LINK_TYPE="${LINK_TYPE:-static}"
SANITIZER="${SANITIZER:-off}"
COMPILER="${COMPILER:-}"
BOOST_LIBS="${BOOST_LIBS:---with-json --with-program_options --with-charconv}"

BOOST_VERSION_DASH="${BOOST_VERSION//./_}"
BOOST_URL="${BOOST_URL:-https://archives.boost.io/beta/1.92.0.beta1/source/boost_$BOOST_VERSION_DASH.tar.gz}"

wget -q "$BOOST_URL"
tar -xf "boost_$BOOST_VERSION_DASH.tar.gz"
if [ -d "boost_$BOOST_VERSION_DASH" ]; then
    BOOST_DIR="boost_$BOOST_VERSION_DASH"
else
    BOOST_DIR=$(ls -d boost_*/)
fi
cd "$BOOST_DIR"
sh bootstrap.sh

# shellcheck disable=SC2086
if [ "$SANITIZER" != "off" ]; then
    case "$SANITIZER" in
        asan)  SANITIZER_FLAGS="-fsanitize=address -fno-omit-frame-pointer" ;;
        tsan)  SANITIZER_FLAGS="-fsanitize=thread" ;;
        ubsan) SANITIZER_FLAGS="-fsanitize=undefined" ;;
        msan)  SANITIZER_FLAGS="-fsanitize=memory -fsanitize-memory-track-origins" ;;
        *)     echo "Unknown sanitizer: $SANITIZER"; exit 1 ;;
    esac
    if [ "$COMPILER" = "clang" ] || [ "$SANITIZER" = "msan" ]; then
        TOOLSET="toolset=clang"
        # b2 with toolset=clang forces --target=x86_64-pc-linux, which breaks
        # the libstdc++ header lookup on musl. Pin the native target instead.
        CLANG_TARGET="-target $(clang -dumpmachine)"
    else
        TOOLSET=""
        CLANG_TARGET=""
    fi
    # MSAN needs the instrumented libc++ (built by build-libcxx-msan.sh).
    STDLIB_FLAGS=""
    STDLIB_LINK=""
    if [ "$SANITIZER" = "msan" ]; then
        STDLIB_FLAGS="-stdlib=libc++ -nostdinc++ -isystem /usr/local/include/c++/v1 -fPIC"
        STDLIB_LINK="-stdlib=libc++ -L/usr/local/lib -Wl,-rpath,/usr/local/lib"
    fi
    # shellcheck disable=SC2086
    ./b2 install \
        $BOOST_LIBS \
        variant=release \
        debug-symbols=on \
        link=shared runtime-link=shared \
        $TOOLSET \
        cxxflags="$CLANG_TARGET $SANITIZER_FLAGS $STDLIB_FLAGS -g -O1" \
        linkflags="$CLANG_TARGET $SANITIZER_FLAGS $STDLIB_LINK" \
        -j2
elif [ "$BUILD_VARIANT" = "Debug" ]; then
    ./b2 install \
        $BOOST_LIBS \
        variant=debug debug-symbols=on link=$LINK_TYPE runtime-link=$LINK_TYPE \
        -j2
else
    ./b2 install \
        $BOOST_LIBS \
        variant=release debug-symbols=off link=$LINK_TYPE runtime-link=$LINK_TYPE optimization=speed \
        -j2
fi

cd ..
rm -rf "$BOOST_DIR" "boost_$BOOST_VERSION_DASH.tar.gz"
