#!/bin/bash
# Boost Software License - Version 1.0 - August 17th, 2003
#
# Copyright (c) 2026 Ian Torres
#
# Permission is hereby granted, free of charge, to any person or organization
# obtaining a copy of the software and accompanying documentation covered by
# this license (the "Software") to use, reproduce, display, distribute,
# execute, and transmit the Software, and to prepare derivative works of the
# Software, and to permit third-parties to whom the Software is furnished to
# do so, all subject to the following:
#
# The copyright notices in the Software and this entire statement, including
# the above license grant, this restriction and the following disclaimer,
# must be included in all copies of the Software, in whole or in part, and
# all derivative works of the Software, unless such copies or derivative
# works are solely in the form of machine-executable object code generated by
# a source language processor.
set -euo pipefail

SANITIZER="${SANITIZER:-off}"
LLVM_PROJECT_TAG="${LLVM_PROJECT_TAG:-}"

if [ "$SANITIZER" != "msan" ]; then
    echo "libc++ MSAN build skipped (SANITIZER=$SANITIZER)"
    exit 0
fi

# MSAN requires the whole C++ stdlib to be instrumented. The distro libstdc++
# is not, so build libc++/libc++abi from the LLVM sources matching the image
# clang and install over /usr/local.
if [ -z "$LLVM_PROJECT_TAG" ]; then
    case "$(clang --version | head -1)" in
        *clang\ version\ 18*) LLVM_PROJECT_TAG="llvmorg-18.1.8" ;;
        *clang\ version\ 14*) LLVM_PROJECT_TAG="llvmorg-14.0.6" ;;
        *) echo "Unsupported clang version for MSAN libc++ build"; exit 1 ;;
    esac
fi

wget -q "https://github.com/llvm/llvm-project/archive/refs/tags/$LLVM_PROJECT_TAG.tar.gz" -O /tmp/llvm-project.tar.gz
cd /tmp
tar -xf llvm-project.tar.gz
if [ -d "llvm-project-${LLVM_PROJECT_TAG#llvmorg-}" ]; then
    mv "llvm-project-${LLVM_PROJECT_TAG#llvmorg-}" llvm-project
else
    mv "$(ls -d llvm-project-*/)" llvm-project
fi
cd llvm-project

# LLVM_USE_SANITIZER is the documented way to instrument libc++: it adds the
# sanitizer flags to the runtime build AND keeps -nostdinc++ so libc++'s own
# headers are used instead of GCC's libstdc++ ones.
cmake -S runtimes -B build -G Ninja \
    -DLLVM_ENABLE_RUNTIMES="libcxx;libcxxabi" \
    -DCMAKE_C_COMPILER=clang \
    -DCMAKE_CXX_COMPILER=clang++ \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=/usr/local \
    -DLLVM_USE_SANITIZER=MemoryWithOrigins \
    -DLIBCXX_ENABLE_SHARED=ON \
    -DLIBCXX_ENABLE_STATIC=OFF \
    -DLIBCXXABI_ENABLE_SHARED=ON \
    -DLIBCXXABI_ENABLE_STATIC=OFF \
    -DLIBCXX_ENABLE_EXPERIMENTAL_LIBRARY=OFF \
    -DLIBCXX_ENABLE_STATIC_ABI_LIBRARY=OFF \
    -DLIBCXXABI_ENABLE_EXCEPTIONS=ON

cmake --build build --target install-cxx install-cxxabi --parallel 2
rm -rf /tmp/llvm-project /tmp/llvm-project.tar.gz
