#!/bin/bash
# Boost Software License - Version 1.0 - August 17th, 2003
#
# Copyright (c) 2026 Ian Torres
#
# Permission is hereby granted, free of charge, to any person or organization
# obtaining a copy of the software and accompanying documentation covered by
# this license (the "Software") to use, reproduce, display, distribute,
# execute, and transmit the Software, and to prepare derivative works of the
# Software, and to permit third-parties to whom the Software is furnished to
# do so, all subject to the following:
#
# The copyright notices in the Software and this entire statement, including
# the above license grant, this restriction and the following disclaimer,
# must be included in all copies of the Software, in whole or in part, and
# all derivative works of the Software, unless such copies or derivative
# works are solely in the form of machine-executable object code generated by
# a source language processor.
set -euo pipefail

BOOST_VERSION="${BOOST_VERSION:-1.92.0_b1}"
BUILD_VARIANT="${BUILD_VARIANT:-Release}"
LINK_TYPE="${LINK_TYPE:-static}"
BOOST_LIBS="${BOOST_LIBS:---with-json --with-program_options --with-charconv}"

BOOST_VERSION_DASH="${BOOST_VERSION//./_}"
BOOST_URL="${BOOST_URL:-https://archives.boost.io/beta/1.92.0.beta1/source/boost_$BOOST_VERSION_DASH.tar.gz}"

wget -q "$BOOST_URL"
tar -xf "boost_$BOOST_VERSION_DASH.tar.gz"
if [ -d "boost_$BOOST_VERSION_DASH" ]; then
    BOOST_DIR="boost_$BOOST_VERSION_DASH"
else
    BOOST_DIR=$(ls -d boost_*/)
fi
cd "$BOOST_DIR"
sh bootstrap.sh

# shellcheck disable=SC2086
if [ "$BUILD_VARIANT" = "Debug" ]; then
    ./b2 install \
        $BOOST_LIBS \
        variant=debug debug-symbols=on link=$LINK_TYPE runtime-link=$LINK_TYPE \
        -j2
else
    ./b2 install \
        $BOOST_LIBS \
        variant=release debug-symbols=off link=$LINK_TYPE runtime-link=$LINK_TYPE optimization=speed \
        -j2
fi

cd ..
rm -rf "$BOOST_DIR" "boost_$BOOST_VERSION_DASH.tar.gz"
