#!/bin/bash
# Boost Software License - Version 1.0 - August 17th, 2003
#
# Copyright (c) 2026 Ian Torres
#
# Permission is hereby granted, free of charge, to any person or organization
# obtaining a copy of the software and accompanying documentation covered by
# this license (the "Software") to use, reproduce, display, distribute,
# execute, and transmit the Software, and to prepare derivative works of the
# Software, and to permit third-parties to whom the Software is furnished to
# do so, all subject to the following:
#
# The copyright notices in the Software and this entire statement, including
# the above license grant, this restriction and the following disclaimer,
# must be included in all copies of the Software, in whole or in part, and
# all derivative works of the Software, unless such copies or derivative
# works are solely in the form of machine-executable object code generated by
# a source language processor.
set -euo pipefail

GTEST_VERSION="${GTEST_VERSION:-v1.16.0}"
BUILD_VARIANT="${BUILD_VARIANT:-Release}"
LINK_TYPE="${LINK_TYPE:-static}"
SANITIZER="${SANITIZER:-off}"
COMPILER="${COMPILER:-}"

SHARED=OFF
if [ "$LINK_TYPE" = "shared" ] || [ "$SANITIZER" != "off" ]; then
    SHARED=ON
fi

wget -q "https://github.com/google/googletest/archive/refs/tags/$GTEST_VERSION.tar.gz" -O /tmp/googletest.tar.gz
cd /tmp
tar -xf googletest.tar.gz
mv "googletest-${GTEST_VERSION#v}" googletest
cd googletest

CMAKE_ARGS=(
    -DCMAKE_BUILD_TYPE="$BUILD_VARIANT"
    -DBUILD_GMOCK=ON
    -DBUILD_SHARED_LIBS="$SHARED"
    -DINSTALL_GTEST=ON
)

if [ "$SANITIZER" != "off" ]; then
    case "$SANITIZER" in
        asan)  SANITIZER_FLAGS="-fsanitize=address -fno-omit-frame-pointer" ;;
        tsan)  SANITIZER_FLAGS="-fsanitize=thread" ;;
        ubsan) SANITIZER_FLAGS="-fsanitize=undefined" ;;
        msan)  SANITIZER_FLAGS="-fsanitize=memory -fsanitize-memory-track-origins" ;;
        *)     echo "Unknown sanitizer: $SANITIZER"; exit 1 ;;
    esac
    if [ "$COMPILER" = "clang" ] || [ "$SANITIZER" = "msan" ]; then
        CMAKE_ARGS+=(
            -DCMAKE_C_COMPILER=clang
            -DCMAKE_CXX_COMPILER=clang++
        )
    fi
    # MSAN needs the instrumented libc++ (built by build-libcxx-msan.sh).
    STDLIB_FLAGS=""
    STDLIB_LINK=""
    if [ "$SANITIZER" = "msan" ]; then
        STDLIB_FLAGS="-stdlib=libc++ -nostdinc++ -isystem /usr/local/include/c++/v1 -fPIC"
        STDLIB_LINK="-stdlib=libc++ -L/usr/local/lib -Wl,-rpath,/usr/local/lib"
    fi
    CMAKE_ARGS+=(
        -DCMAKE_CXX_FLAGS="$SANITIZER_FLAGS $STDLIB_FLAGS -g -O1"
        -DCMAKE_EXE_LINKER_FLAGS="$SANITIZER_FLAGS $STDLIB_LINK"
        -DCMAKE_SHARED_LINKER_FLAGS="$SANITIZER_FLAGS $STDLIB_LINK"
    )
fi

cmake -S . -B build "${CMAKE_ARGS[@]}"
cmake --build build --target install --parallel 2
rm -rf /tmp/googletest /tmp/googletest.tar.gz
